CREATE DATABASE IF NOT EXISTS formation;
USE formation;
CREATE TABLE IF NOT EXISTS utilisateurs (
    id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    nom VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL
);
